server:
  port: 8761

eureka:
  server:
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaltZone: http://${eureka.instance.hostname}:${server.port}/eureka/